services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Senha123"

  admin:
    image: elestio/pgadmin
    restart: always
    ports:
      - 8080:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: root@unimar.br
      PGADMIN_DEFAULT_PASSWORD: Senha123
      PGADMIN_LISTEN_PORT: 8080
        